### ISSUE TITLE
Rebooting on every boot.

### ISSUE THREAD

**Issue by iAmSaugata** [jokob-sk/Pi.Alert#119]
**Describe the issue**
Keep rebooting itself after deployment. I know there is another issue reported, but the error I am getting in the log is not identical, hence I have opened this.

```
    Devices in this cycle..: 20
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0
Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name...
        Names updated:  0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...
Check if something to report...
Changes detected, sending reports...
    Sending report by email...
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 191, in main
    email_reporting()
  File "/home/pi/pialert/back/pialert.py", line 1584, in email_reporting
    if REPORT_APPRISE and check_config('apprise'):
NameError: name 'REPORT_APPRISE' is not defined
Nothing to do here.
sed: cannot rename /home/pi/pialert/config/pialert.conf: Device or resource busy
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
sudo: unable to resolve host pialert: Name or service not known
Loop start
---------------------------
Check Internet IP
    Timestamp:2022-12-17 18:10:00
    Retrieving Internet IP...
   xx.xx.xx.xx
    Retrieving previous IP...
   xx.xx.xx.xx
    No changes to perform
    Skipping Dynamic DNS update...

Scan Devices
    ScanCycle:1
    Timestamp:2022-12-17 18:10:00
Scanning...
    arp-scan Method...
    arp-scan: One interface
    Pi-hole Method...
    DHCP Leases Method...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2352, in <module>
Processing scan results...
    Devices Detected.......:20
        arp-scan Method....:18
        Pi-hole Method.....: +0
        New Devices........: 0
    Devices in this cycle..: 20
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0
Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name...
        Names updated:  0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...
Check if something to report...
Changes detected, sending reports...
    Sending report by email...
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 191, in main
    email_reporting()
  File "/home/pi/pialert/back/pialert.py", line 1584, in email_reporting
    if REPORT_APPRISE and check_config('apprise'):
NameError: name 'REPORT_APPRISE' is not defined
Nothing to do here.
sed: cannot rename /home/pi/pialert/config/pialert.conf: Device or resource busy
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
sudo: unable to resolve host pialert: Name or service not known
```

**Comment by jokob-sk** [comment]
Hey!

Please re-download the image and the latest `pialert.conf` (or compare yours and the latest one).  E.g. you seem to be missing `REPORT_APPRISE`. I will make the next release more stable when it comes to users with old config files. 

Thanks for the patience!

j

**Comment by iAmSaugata** [comment]
Rebooting stopped now, but I am still getting multiple error in the console.

```
12/18/2022 12:55:38 PM
Traceback (most recent call last):
12/18/2022 12:55:38 PM
  File "/home/pi/pialert/back/pialert.py", line 2352, in <module>
12/18/2022 12:55:38 PM
    sys.exit(main())       
12/18/2022 12:55:38 PM
  File "/home/pi/pialert/back/pialert.py", line 187, in main
12/18/2022 12:55:38 PM
    scan_network() 
12/18/2022 12:55:38 PM
  File "/home/pi/pialert/back/pialert.py", line 539, in scan_network
12/18/2022 12:55:38 PM
    arpscan_devices = execute_arpscan ()
12/18/2022 12:55:38 PM
  File "/home/pi/pialert/back/pialert.py", line 631, in execute_arpscan
12/18/2022 12:55:38 PM
    if type(SCAN_SUBNETS) is list:
12/18/2022 12:55:38 PM
NameError: name 'SCAN_SUBNETS' is not defined
12/18/2022 12:56:01 PM
Nothing to do here.
12/18/2022 12:56:01 PM
sed: cannot rename /home/pi/pialert/config/pialert.conf: Device or resource busy
12/18/2022 12:56:01 PM
mkdir: cannot create directory '/run/php': File exists
12/18/2022 12:56:01 PM
Starting nginx: nginx.
12/18/2022 12:56:03 PM
sudo: unable to resolve host pialert: Name or service not known
12/18/2022 1:01:19 PM
sudo: unable to resolve host pialert: Name or service not known
12/18/2022 1:04:58 PM
Nothing to do here.
12/18/2022 1:04:58 PM
sed: cannot rename /home/pi/pialert/config/pialert.conf: Device or resource busy
12/18/2022 1:04:58 PM
mkdir: cannot create directory '/run/php': File exists
```

**Comment by jokob-sk** [comment]
Hey,

`sudo: unable to resolve host pialert: Name or service not known` this points to not having the SCAN_SUBNETS variable configured properly.

Example for multiple interfaces:

`SCAN_SUBNETS            = ['192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0']`

Example for one interface:

`SCAN_SUBNETS            = '192.168.1.0/24 --interface=eth1'`

Check the readme for details: https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles#config-pialertconf

**Comment by iAmSaugata** [comment]
![image](https://user-images.githubusercontent.com/26755120/208289004-a9a1ca5a-4b52-4ba7-9b0d-46be025f8b4d.png)

My subnet scan working just fine, but still getting this.

![image](https://user-images.githubusercontent.com/26755120/208289033-5255b1b6-2b07-4b31-8311-6ee0e0a5e982.png)

**Comment by jokob-sk** [comment]
I still don't think your subnet variable is correct,  can you try configuring it as per instructions? Try to add the interface attribute as well.

**Comment by jokob-sk** [comment]
Also make sure you give read access to the config file.

**Comment by iAmSaugata** [comment]
> Also make sure you give read access to the config file.

Lookup issue fixed, as it was trying to lookup it's hostname on network, I have created one A record for it. Permission issue still there with config file, not sure why. I gave full access to the file already.

**Comment by jokob-sk** [comment]
Can you post your full `pialert.conf` file?

**Comment by iAmSaugata** [comment]
> Can you post your full `pialert.conf` file?

```
#-------------------------------------------------------------------------------
#  Pi.Alert
#  Open Source Network Guard / WIFI & LAN intrusion detector 
#
#  pialert.conf - Back module. Configuration file
#-------------------------------------------------------------------------------
#  Puche 2021        pi.alert.application@gmail.com        GNU GPLv3
#-------------------------------------------------------------------------------

# GENERAL settings
# ----------------------

PRINT_LOG               = False
TIMEZONE                = 'Europe/Berlin'
PIALERT_WEB_PROTECTION  = False
PIALERT_WEB_PASSWORD    = '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'

INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices', 'events']   # Specifies which events trigger notifications. 
                                                                                  # Remove the event type(s) you don't want to get notified on 
                                                                                  # Overrides device-specific settings in the UI.
SCAN_CYCLE_MINUTES      = 5            # delay between scans

# EMAIL settings
# ----------------------
SMTP_SERVER             = 'email-smtp.ap-south-1.amazonaws.com'
SMTP_PORT               = '587'
SMTP_USER               = 'xxxxxxxxxxxxxxxxxxx'
SMTP_PASS               = 'xxxxxxxxxxxxxxxxxxxxxxx'
SMTP_SKIP_TLS           = False
SMTP_SKIP_LOGIN         = False

REPORT_MAIL       = True
REPORT_FROM       = 'webadmin@xxxxxxxxxx'
REPORT_TO         = 'xxxxxxxxx@outlook.in'
REPORT_DEVICE_URL = 'https://pialert.xxxxxxxxxxxxx/pialert/deviceDetails.php?mac='
REPORT_DASHBOARD_URL    = 'https://pialert.xxxxxxxxxxxxx/'

# Webhook settings
# ----------------------
REPORT_WEBHOOK          = False
WEBHOOK_URL             = 'http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD         = 'json'       # webhook payload data format for the "body > attachements > text" attribute 
                                       # in https://github.com/jokob-sk/Pi.Alert/blob/main/docs/webhook_json_sample.json 
                                       #   supported values: 'json', 'html' or 'text'
                                       #   e.g.: for discord use 'html'
WEBHOOK_REQUEST_METHOD  = 'GET'        # POST, GET...

# Apprise settings
#-----------------------
REPORT_APPRISE          = False
APPRISE_HOST            = 'http://localhost:8000/notify'
APPRISE_URL             = 'mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'

# NTFY (https://ntfy.sh/) settings
# ----------------------
REPORT_NTFY             = False
NTFY_HOST               = 'https://ntfy.sh'
NTFY_TOPIC              = 'replace_my_secure_topicname_91h889f28'
NTFY_USER               = 'user'       # set username... 
NTFY_PASSWORD           = 'passw0rd'   # ...and password if authentication is used https://docs.ntfy.sh/config/#users-and-roles

# PUSHSAFER (https://www.pushsafer.com/) settings
# ----------------------
REPORT_PUSHSAFER        = False
PUSHSAFER_TOKEN         = 'ApiKey'

# MQTT settings
# ----------------------
REPORT_MQTT             = False
MQTT_BROKER             = '192.168.1.2'
MQTT_PORT               = 1883
MQTT_USER               = 'mqtt'
MQTT_PASSWORD           = 'passw0rd'
MQTT_QOS                = 0
MQTT_DELAY_SEC          = 2            # delay in seconds, increase if not all devices are created in Home Assistant

# DynDNS
# ----------------------
# QUERY_MYIP_SERVER       = 'https://diagnostic.opendns.com/myip'
QUERY_MYIP_SERVER       = 'http://ipv4.icanhazip.com'
DDNS_ACTIVE             = False
DDNS_DOMAIN             = 'your_domain.freeddns.org'
DDNS_USER               = 'dynu_user'
DDNS_PASSWORD           = 'A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL         = 'https://api.dynu.com/nic/update?'

# PIHOLE settings
# ----------------------
PIHOLE_ACTIVE           = False                         # if enabled you need to map '/etc/pihole/pihole-FTL.db' in docker-compose.yml
PIHOLE_DB               = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE             = False                         # if enabled you need to map '/etc/pihole/dhcp.leases' in docker-compose.yml
DHCP_LEASES             = '/etc/pihole/dhcp.leases'

# arp-scan options & samples
# ----------------------
#
# Scan local network (default)
# SCAN_SUBNETS    = '--localnet'
#
# Scan two subnets
# SCAN_SUBNETS    = '192.168.0.39/32 192.168.0.47/32 192.168.0.0/24'
# SCAN_SUBNETS    = '"192.168.0.47/32" "192.168.0.39/32" "192.168.0.1/24"'
SCAN_SUBNETS = '192.168.0.0/24 --interface=eth0'
#
# Scan using interface eth0
# SCAN_SUBNETS    = '--localnet --interface=eth0'
#
# Scan multiple interfaces (eth1 and eth0):
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]

#SCAN_SUBNETS            = '--localnet'

#SCAN_SUBNETS      = '192.168.0.0/24 192.168.29.0/24'

# Maintenance Task Settings
# ----------------------
DAYS_TO_KEEP_EVENTS = 90
```

**Comment by jokob-sk** [comment]
Humm, looks good. 

can you check how the permissions look like inside of the container? 

![image](https://user-images.githubusercontent.com/96159884/209236687-a6d7ed0d-01cd-43c9-b7a5-bb4d07467aba.png)

**Comment by jokob-sk** [comment]
I also pushed a new image with more logging info today, so you can try to download it and see if it helps.

**Comment by jokob-sk** [comment]
I'm closing this for now as there was no reply for almost a week. Will re-open if needed.
