### ISSUE TITLE
Unable to import devices.csv

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/Pi.Alert#137]
**Describe the issue**
After the last update it is impossible to import the device csv file. (device.csv)

If I export the file from one installation and then try to import it into another installation (same version) I get the following error...

`The CSV file couldn't be imported. Make sure the format is correct.  
INSERT INTO Devices (dev_MAC,dev_Name,dev_Owner,dev_DeviceType,dev_Vendor,dev_Favorite,dev_Group,dev_Comments,dev_FirstConnection,dev_LastConnection,dev_LastIP,dev_StaticIP,dev_ScanCycle,dev_LogEvents,dev_AlertEvents,dev_AlertDeviceDown,dev_SkipRepeated,dev_LastNotification,dev_PresentLastScan,dev_NewDevice,dev_Location,dev_Archived,dev_Network_Node_port,dev_Network_Node_MAC_ADDR) VALUES ("") 1 values for 24 columns`

Please fix.
Thank you

**Comment by jokob-sk** [comment]
Hi there!

Thanks for reaching out!

I just tried and seems to be working fine on my end:

![image](https://user-images.githubusercontent.com/96159884/210072354-1b5e9c07-e3f6-4bbb-8da5-09aa2ecea373.png)

Please make sure permissions are setup correctly on your server and check the logs if there are related logs.

You can also try to generate a new CSV file to make sure the format is correct.

Hope this helps,
j

**Comment by corasaniti** [comment]
@jokob-sk 
unfortunately it still doesn't work for me. If I export and then import I get the following error. 
Maybe I'm using a broken build. I attach screen

![Cattura2](https://user-images.githubusercontent.com/5001932/210076741-3ead205a-2e0a-41e5-a813-f4edc8353c04.png)

![Cattura1](https://user-images.githubusercontent.com/5001932/210076748-be3a00ce-84ec-44b8-8efb-84da55f2e9d3.PNG)

**Comment by corasaniti** [comment]
@jokob-sk 
There is something wrong with the permissions. Does this log tell you anything?
Thank you


```
[upgradeDB] Re-creating Parameters table
[upgradeDB] Re-creating Settings table
[2022-12-30 15:28:46] Config: Imported new config
[2022-12-30 15:28:46] Process: Start
[2022-12-30 15:28:46] Check Internet IP:
    Retrieving Internet IP:
      X.X.X.X
    Retrieving previous IP:
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 635, in main
    check_internet_IP()
  File "/home/pi/pialert/back/pialert.py", line 723, in check_internet_IP
    previous_IP = get_previous_internet_IP ()
  File "/home/pi/pialert/back/pialert.py", line 822, in get_previous_internet_IP
    previous_IP = sql.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
 Permissions check (All should be True)
------------------------------------------------
  /config/pialert.conf |  READ  | True
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 3153, in <module>
  /config/pialert.conf |  WRITE | True
  /db/pialert.db       |  READ  | True
  /db/pialert.db       |  WRITE | True
------------------------------------------------
[upgradeDB] Re-creating Parameters table
[upgradeDB] Re-creating Settings table
[2022-12-30 15:28:52] Config: Imported new config
[2022-12-30 15:28:52] Process: Start
[2022-12-30 15:28:52] Check Internet IP:
    Retrieving Internet IP:
      X.X.X.X
    Retrieving previous IP:
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 635, in main
    check_internet_IP()
  File "/home/pi/pialert/back/pialert.py", line 723, in check_internet_IP
    previous_IP = get_previous_internet_IP ()
  File "/home/pi/pialert/back/pialert.py", line 822, in get_previous_internet_IP
    previous_IP = sql.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
 Permissions check (All should be True)
------------------------------------------------
  /config/pialert.conf |  READ  | True
  /config/pialert.conf |  WRITE | True
  /db/pialert.db       |  READ  | True
  /db/pialert.db       |  WRITE | True
------------------------------------------------
[upgradeDB] Re-creating Parameters table
[upgradeDB] Re-creating Settings table
[2022-12-30 15:29:01] Config: Imported new config
[2022-12-30 15:29:01] Process: Start
[2022-12-30 15:29:00] Check Internet IP:
    Retrieving Internet IP:
      X.X.X.X
    Retrieving previous IP:
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 3153, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 635, in main
    check_internet_IP()
  File "/home/pi/pialert/back/pialert.py", line 723, in check_internet_IP
    previous_IP = get_previous_internet_IP ()
  File "/home/pi/pialert/back/pialert.py", line 822, in get_previous_internet_IP
    previous_IP = sql.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
 Permissions check (All should be True)
------------------------------------------------
  /config/pialert.conf |  READ  | True
  /config/pialert.conf |  WRITE | True
  /db/pialert.db       |  READ  | True
  /db/pialert.db       |  WRITE | True
------------------------------------------------
[upgradeDB] Re-creating Parameters table
[upgradeDB] Re-creating Settings table
[2022-12-30 15:29:16] Config: Imported new config
[2022-12-30 15:29:16] Process: Start
[2022-12-30 15:29:15] Check Internet IP:
    Retrieving Internet IP:
      X.X.X.X
    Retrieving previous IP:
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 3153, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 635, in main
    check_internet_IP()
  File "/home/pi/pialert/back/pialert.py", line 723, in check_internet_IP
    previous_IP = get_previous_internet_IP ()
  File "/home/pi/pialert/back/pialert.py", line 822, in get_previous_internet_IP
    previous_IP = sql.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by corasaniti** [comment]
@jokob-sk 
I have solved by importing the entire database (pialert.db file). I think it's a permissions problem but I don't understand.
I closed the issue
Thank you

**Comment by jokob-sk** [comment]
Hey,

Thanks for sending me the error

```bash
  File "/home/pi/pialert/back/pialert.py", line 3153, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 635, in main
    check_internet_IP()
  File "/home/pi/pialert/back/pialert.py", line 723, in check_internet_IP
    previous_IP = get_previous_internet_IP ()
  File "/home/pi/pialert/back/pialert.py", line 822, in get_previous_internet_IP
    previous_IP = sql.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

```
Will be fixed in the next release.

**Comment by AquaGoat** [comment]
I encountered the exact same issue as the user who opened this. The issue is that your CSV export contains two blank rows first, before the header row with the column names.

If you export the CSV from Pi Alert, delete the top two blank rows from the devices.csv, place in your pialert/config directory, the import will then work.
