### ISSUE TITLE
Container enters loopless restart

### ISSUE THREAD

**Issue by tamimology** [jokob-sk/Pi.Alert#171]
**Describe the issue**
I updated to the latest version on Feb 6th and since then it is not staying on, it keeps on restarting. I did remove the container and recreated it again a couple of times, still the same. I also deleted the image and pulled it again from docker hub, and still, the issue persists. So when I checked the logs, I got the below

**Paste last few lines from `pialert.log`**

```

    Inserting scan results into Online_History
    Skipping repeated notifications
[2023-02-06 15:23:14] Scan: Nmap for max 150s (2.5min) per device
        Estimated max delay: 450s (7.5min)
[2023-02-06 15:23:39] Scan: Nmap SUCCESS for 192.168.1.2 (1/3)
[2023-02-06 15:23:39] Scan: Nmap found 4 new or changed ports
[2023-02-06 15:23:57] Scan: Nmap SUCCESS for 192.168.1.25 (2/3)
[2023-02-06 15:23:57] Scan: Nmap found 2 new or changed ports
[2023-02-06 15:23:58] Scan: Nmap SUCCESS for 192.168.1.100 (3/3)
  Check if something to report
     [API] Updating files in /front/api
    write_file(folder + 'notification_text.txt'  , mail_text)
  File "/home/pi/pialert/back/pialert.py", line 3167, in write_file
    file = open (pPath, 'w', encoding='utf-8') 
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/pialert/front/api/notification_text.txt'
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
 Permissions check (All should be True)
------------------------------------------------
  /config/pialert.conf |  READ  | True
  /config/pialert.conf |  WRITE | True
  /db/pialert.db       |  READ  | True
  /db/pialert.db       |  WRITE | True
------------------------------------------------
[Setup] Attempting to fix permissions.
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 3471, in <module>
[Setup] Attempting to fix permissions.
[upgradeDB] Re-creating Settings table
[upgradeDB] Re-creating Parameters table
[2023-02-06 15:24:03] Config: Imported new config
[2023-02-06 15:24:03] Process: Start
[2023-02-06 15:24:02] Check Internet IP:
    Retrieving Internet IP:
      194.223.40.176
    Retrieving previous IP:
      194.223.40.176
    No changes to perform
    Skipping Dynamic DNS update
[2023-02-06 15:24:03] Scan: Pholus for 600s (10.0min)
        Pholus scan on [interface] bond0 [mask] --localnet
usage: pholus3.py [-h] [-rpcap] [-dns] [-4] [-6] [-hl HLIMIT] [-rq] [-rp]
                  [-ll] [-s6 SOURCE6] [-s4 SOURCE4] [-d6 D6] [-d4 D4]
                  [-qtype QTYPE] [-query QUERY] [-qclass Q_CLASS] [-qu]
                  [-dns_response DNS_RESPONSE] [-sttl] [-rm] [-tm TARGET_MAC]
                  [-sm SOURCE_MAC] [-stimeout SNIFFER_TIMEOUT]
                  [-domain DOMAIN] [-rdns_scanning RDNS_SCANNING] [-sscan]
                  [-ttl TTL] [-dos_ttl] [-conflict] [-afre] [-printer]
                  [-airplay] [-workstation] [-googlecast] [-fl]
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 599, in main
    send_notifications()
  File "/home/pi/pialert/back/pialert.py", line 2281, in send_notifications
                  [-flooding-interval FLOODING_INTERVAL]
                  [-ftimeout FLOODING_TIMEOUT]
                  interface
pholus3.py: error: argument -rdns_scanning/--reverse_dns_scanning: expected one argument
        Error - Pholus Scan - check logs
[2023-02-06 15:24:06] Scan: Pholus FAIL - check logs
[2023-02-06 15:24:02] Scan Devices:
    arp-scan start
  Processing scan results
    Devices Detected.......: 19
        arp-scan detected..: 17
        Pi-hole detected...: +0
        New Devices........: 0
    Devices in this cycle..: 19
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0
  Updating DB Info
    Sessions Events (connect / discconnect)
    update_api(True)
  File "/home/pi/pialert/back/pialert.py", line 3100, in update_api
    Creating new devices
    Updating Devices Info
    Voiding false (ghost) disconnections
    Pairing session events (connection / disconnection) 
    Creating sessions snapshot
    Inserting scan results into Online_History
    Skipping repeated notifications
[2023-02-06 15:24:19] Scan: Nmap for max 150s (2.5min) per device
        Estimated max delay: 450s (7.5min)
[2023-02-06 15:24:45] Scan: Nmap SUCCESS for 192.168.1.2 (1/3)
[2023-02-06 15:24:45] Scan: Nmap found 4 new or changed ports
[2023-02-06 15:25:00] Scan: Nmap SUCCESS for 192.168.1.25 (2/3)
[2023-02-06 15:25:00] Scan: Nmap found 2 new or changed ports
[2023-02-06 15:25:01] Scan: Nmap SUCCESS for 192.168.1.100 (3/3)
  Check if something to report
     [API] Updating files in /front/api
    write_file(folder + 'notification_text.txt'  , mail_text)
  File "/home/pi/pialert/back/pialert.py", line 3167, in write_file
    file = open (pPath, 'w', encoding='utf-8') 
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/pialert/front/api/notification_text.txt'
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.

```

**Paste your `pialert.conf` (remove personal info)**

```

#-------------------------------------------------------------------------------
#  Pi.Alert
#  Open Source Network Guard / WIFI & LAN intrusion detector 
#
#  pialert.conf - Back module. Configuration file
#-------------------------------------------------------------------------------
#  Puche 2021        pi.alert.application@gmail.com        GNU GPLv3
#-------------------------------------------------------------------------------

PIALERT_PATH            = '/home/pi/pialert'
DB_PATH                 = PIALERT_PATH + '/db/pialert.db'
LOG_PATH                = PIALERT_PATH + '/log'
VENDORS_DB              = '/usr/share/arp-scan/ieee-oui.txt'
PRINT_LOG               = False
TIMEZONE                = 'Australia/Melbourne'
PIALERT_WEB_PROTECTION  = False
PIALERT_WEB_PASSWORD    = ''

# EMAIL settings
# ----------------------
SMTP_SERVER             = 'smtp.gmail.com'
SMTP_PORT               = 587
SMTP_USER               = 'user@gmail.com'
SMTP_PASS               = 'password'
SMTP_SKIP_TLS	        = False
SMTP_SKIP_LOGIN	        = False

REPORT_MAIL             = False
REPORT_FROM             = 'Pi.Alert <' + SMTP_USER +'>'
REPORT_TO               = 'user@gmail.com'
REPORT_DEVICE_URL       = 'http://pi.alert/deviceDetails.php?mac='
REPORT_DASHBOARD_URL    = 'http://pi.alert/'

# Webhook settings
# ----------------------
REPORT_WEBHOOK          = False
WEBHOOK_URL             = 'http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
# webhook payload data format for the "body > attachements > text" attribute in https://github.com/jokob-sk/Pi.Alert/blob/main/docs/webhook_json_sample.json
#   supported values: 'json' or 'html' 
#   e.g.: for discord use 'html'
WEBHOOK_PAYLOAD         = 'json'  

# Apprise settings
#-----------------------
REPORT_APPRISE          = True
APPRISE_HOST            = 'http://192.168.1.10:8001/notify'
APPRISE_URL             = 'pover://'

# NTFY (https://ntfy.sh/) settings
# ----------------------
REPORT_NTFY             = False
NTFY_TOPIC              = 'replace_my_secure_topicname_91h889f28'

# PUSHSAFER (https://www.pushsafer.com/) settings
# ----------------------
REPORT_PUSHSAFER        = False
PUSHSAFER_TOKEN         = 'ApiKey'

# DynDNS
# ----------------------
# QUERY_MYIP_SERVER       = 'https://diagnostic.opendns.com/myip'
QUERY_MYIP_SERVER       = 'http://ipv4.icanhazip.com'
DDNS_ACTIVE             = False
DDNS_DOMAIN             = 'your_domain.freeddns.org'
DDNS_USER               = 'dynu_user'
DDNS_PASSWORD           = 'A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL         = 'https://api.dynu.com/nic/update?'

# PIHOLE settings
# ----------------------
PIHOLE_ACTIVE           = False
PIHOLE_DB               = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE             = False
DHCP_LEASES             = '/var/lib/dhcp/dhcpd.leases' #'/etc/pihole/dhcp.leases'

# arp-scan options & samples
# ----------------------
#
# Scan local network (default)
# SCAN_SUBNETS    = '--localnet'
#
# Scan two subnets
# SCAN_SUBNETS    = '192.168.11.0/24 192.168.144.0/24'
#
# Scan using interface bond0
SCAN_SUBNETS    = '--localnet --interface=bond0'
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=bond0' ]
#
# Scan multiple interfaces (eth1 and eth0):
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]

#SCAN_SUBNETS            = '--localnet'

# Maintenance Tasks Cron
# ----------------------
DAYS_TO_KEEP_EVENTS = 90

```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```

  pialert:
    container_name: pialert
    restart: always
    environment:
      - TZ=$TZ
      - PORT=20211
      - HOST_USER_ID=$PUID
      - HOST_USER_GID=$PGID
    volumes:
      - $PERSIST/pialert:/home/pi/pialert/config
      - $PERSIST/pialert/pialert.db:/home/pi/pialert/db/pialert.db
      - $PERSIST/pialert/logs:/home/pi/pialert/log
      - $PERSIST/pialert/hosts:/etc/hosts
    network_mode: host
    image: 'jokobsk/pi.alert:latest'

```

`.env` 
```

TZ=Australia/Melbourne 
PERSIST=/volume1/docker
PUID=1036
PGID=100

```
**Screenshots**

**Comment by jokob-sk** [comment]
Hey there, this is probably related to this: https://github.com/jokob-sk/Pi.Alert/issues/163#issuecomment-1416509878
