### ISSUE TITLE
Unraid Error

### ISSUE THREAD

**Issue by DJTobi24** [jokob-sk/Pi.Alert#174]
Unraid Container Error Log
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 3471, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 599, in main
    send_notifications()
  File "/home/pi/pialert/back/pialert.py", line 2281, in send_notifications
    update_api(True)
  File "/home/pi/pialert/back/pialert.py", line 3100, in update_api
    write_file(folder + 'notification_text.txt'  , mail_text)
  File "/home/pi/pialert/back/pialert.py", line 3167, in write_file
    file = open (pPath, 'w', encoding='utf-8') 
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/pialert/front/api/notification_text.txt'
mkdir: cannot create directory '/run/php': File exists
pcap_activate: eth1: No such device exists
(SIOCGIFHWADDR: No such device)
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 3471, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 599, in main
    send_notifications()
  File "/home/pi/pialert/back/pialert.py", line 2281, in send_notifications
    update_api(True)
  File "/home/pi/pialert/back/pialert.py", line 3100, in update_api
    write_file(folder + 'notification_text.txt'  , mail_text)
  File "/home/pi/pialert/back/pialert.py", line 3167, in write_file
    file = open (pPath, 'w', encoding='utf-8') 
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/pialert/front/api/notification_text.txt'

**Comment by jokob-sk** [comment]
Solution outlined here: https://github.com/jokob-sk/Pi.Alert/issues/163
