### ISSUE TITLE
[Plugin] Unifi import - connectivity problem with UniFi OS UDM v3.0.20

### ISSUE THREAD

**Issue by pgfeller** [jokob-sk/Pi.Alert#216]
**Unable to connect to UniFi OS UDM v3.0.20**

The current plugin has a problem to connect to UniFi OS UDM 3.0.20. The following log is produced:

```
[LOG_LEVEL=debug] 08:27:23 Skip Repeated end
     [Plugins] Check if any plugins need to be executed on run type: always_after_scan
     [Plugins] ---------------------------------------------
     [Plugins] display_name: UniFi import
     [Plugins] CMD: python3 /home/pi/pialert/front/plugins/unifi_import/script.py username={username} password={password}  host={host} sites={sites}  protocol={protocol} port={port}
     [Plugins] Timeout: 5
        [Plugins]: Pre-Resolved CMD: python3 /home/pi/pialert/front/plugins/unifi_import/script.py username={username} password={password}  host={host} sites={sites}  protocol={protocol} port={port}
        [Plugins]: key     : {username}
        [Plugins]: resolved: ---
        [Plugins]: key     : {password}
        [Plugins]: resolved: ---
        [Plugins]: key     : {host}
        [Plugins]: resolved: 192.168.0.1
        [Plugins]: key     : {sites}
        [Plugins]: resolved: default
        [Plugins]: key     : {protocol}
        [Plugins]: resolved: https://
        [Plugins]: key     : {port}
        [Plugins]: resolved: 8443
        [Plugins]: Resolved     CMD: python3 /home/pi/pialert/front/plugins/unifi_import/script.py username=--- password=---  host=192.168.0.1 sites=default  protocol=https:// port=8443
     [Plugins] Executing: python3 /home/pi/pialert/front/plugins/unifi_import/script.py username={username} password={password}  host={host} sites={sites}  protocol={protocol} port={port}
/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/home/pi/pialert/front/plugins/unifi_import/script.py", line 242, in <module>
      
    main()  
  File "/home/pi/pialert/front/plugins/unifi_import/script.py", line 65, in main
    newEntries = get_entries(newEntries)  
  File "/home/pi/pialert/front/plugins/unifi_import/script.py", line 88, in get_entries
    c = Controller(UNIFI_HOST, UNIFI_USERNAME, UNIFI_PASSWORD, ssl_verify=False, site_id=site )
  File "/usr/local/lib/python3.9/dist-packages/pyunifi/controller.py", line 113, in __init__
    self._login()
  File "/usr/local/lib/python3.9/dist-packages/pyunifi/controller.py", line 195, in _login
    raise APIError(
pyunifi.controller.APIError: Login failed - status code: 404
```

After some tweaking I was able to get the plugin working with a few changes in the docker image (logged in directly and performed the modifications):

  - upgrade of the `pyunifi` library
  - added the `version`parameter to the controller constructor:
    ```python
    c = Controller(UNIFI_HOST, UNIFI_USERNAME, UNIFI_PASSWORD, version='UDMP-unifiOS', ssl_verify=False, site_id=site )
    ```
With this hack the connection and plugin works - therefore I assume that an upgrade of the library with support of the `version` (➡️ `version -- the base version of the controller API [v4|v5|unifiOS|UDMP-unifiOS`) parameter would improve the flexibility of the plugin.

**Comment by jokob-sk** [comment]
Hey,

Thanks for the details!

I've updated this dev image to include a version parameter:

https://hub.docker.com/repository/docker/jokobsk/pi.alert_dev/general

Let me know if this works.

Cheers,
j

**Comment by pgfeller** [comment]
Hi @jokob-sk,

thanks for the fast reaction 🙂. I've upgraded to the new image and can see the new configuration options.
It was possible to etablish a connection and data was exchanged:

```log
     [Plugins] Check if any plugins need to be executed on run type: always_after_scan
     [Plugins] ---------------------------------------------
     [Plugins] display_name: UniFi import
     [Plugins] CMD: python3 /home/pi/pialert/front/plugins/unifi_import/script.py username={username} password={password}  host={host} sites={sites}  protocol={protocol} port={port}
     [Plugins] Timeout: 5
        [Plugins]: Pre-Resolved CMD: python3 /home/pi/pialert/front/plugins/unifi_import/script.py username={username} password={password}  host={host} sites={sites}  protocol={protocol} port={port}
        [Plugins]: key     : {username}
        [Plugins]: resolved: ----
        [Plugins]: key     : {password}
        [Plugins]: resolved: ---
        [Plugins]: key     : {host}
        [Plugins]: resolved: 192.168.0.1
        [Plugins]: key     : {sites}
        [Plugins]: resolved: default
        [Plugins]: key     : {protocol}
        [Plugins]: resolved: https://
        [Plugins]: key     : {port}
        [Plugins]: resolved: 8443
        [Plugins]: Resolved     CMD: python3 /home/pi/pialert/front/plugins/unifi_import/script.py username=--- password=---  host=192.168.0.1 sites=default  protocol=https:// port=8443
     [Plugins] Executing: python3 /home/pi/pialert/front/plugins/unifi_import/script.py username={username} password={password}  host={host} sites={sites}  protocol={protocol} port={port}
[2023-05-04 14:56:34] [Plugins]: SUCCESS, received 258 entries
     [Plugins] Processing        : UNFIMP
     [Plugins] Existing objects        : 28
     [Plugins] New and existing events : 258
```
The devices are also listed in the plugin page:
![image](https://user-images.githubusercontent.com/9395643/236512576-13b0a196-915b-4cb1-9f96-329bb2130843.png)

Let me know what other tests/data you need to check enhancement.

with kind regards,
Patrik

**Comment by jokob-sk** [comment]
Thanks for checking and glad to see it seems to be working!

What would you recommend as the default parameter value (v4/v5...?)?

**Comment by sincze** [comment]
For future reference: "UDMP-unifiOS" also the correct selection to use with the "Cloud Gateway Ultra".

**Comment by jokob-sk** [comment]
@sincze thank you - I will add it to the docs

**Comment by sincze** [comment]
> @sincze thank you - I will add it to the docs

Small addition: **8843** is the port number for that device.

**Comment by jokob-sk** [comment]
@sincze noted 👍:)
