### ISSUE TITLE
SNMP Discovery plug-in is failing

### ISSUE THREAD

**Issue by snerijus** [jokob-sk/Pi.Alert#512]
## Describe the issue

SNMP Discovery plug-in is failing, because front/plugins/snmp_discovery/script.py throws an error:
```
Traceback (most recent call last):
  File "/home/pi/pialert/front/plugins/snmp_discovery/./script.py", line 96, in <module>
    main()
  File "/home/pi/pialert/front/plugins/snmp_discovery/./script.py", line 80, in main
    primaryId   = handleEmpty(macAddress),
                  ^^^^^^^^^^^
NameError: name 'handleEmpty' is not defined
```

The script is missing an import of the  *handleEmpty* method at line 16:
```
from plugin_helper import Plugin_Object, Plugin_Objects, decodeBase64
```

should be:
```
from plugin_helper import Plugin_Object, Plugin_Objects, decodeBase64, handleEmpty
```

**Comment by jokob-sk** [comment]
Hey there,

I think I fixed this in the `pi.alert_dev` image already - can you give it a try? 

j

**Comment by jokob-sk** [comment]
closing as released 🚀
