### ISSUE TITLE
Docker container doesn't start (start loop)

### ISSUE THREAD

**Issue by djzwerg** [jokob-sk/Pi.Alert#544]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

PiAlert won't start - pls look at the log file.

### Expected Behavior

PiAlert should start

### Steps To Reproduce

I'm using a Raspberry Pi 4/8GB (64 Bit) with Docker and Portainer. At the same machine I have PiAlert installed (v23.12.16). I want to use a similar configuration on another location but I'm not able to use ist. I've tried port 20211 as same as 20212.

### pialert.conf

```python
Vanilla file - fresh install
```

### docker-compose.yml

```python
version: "3"
services:
  pialert:
    container_name: my_pialert
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/pi.alert_dev:latest" 
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /docker/pi-alert/db:/home/pi/pialert/db
      - /docker/pi-alert/config:/home/pi/pialert/config/pialert.conf
      - /docker/pi-alert/logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/Berlin      
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20212
```

### What branch are you running?

Production

### pialert.log

```11:04:54 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
      
 
11:04:54 Permissions check (All should be True)
11:04:54 ------------------------------------------------
11:04:54   /config/pialert.conf |  READ  | True
11:04:54   /config/pialert.conf |  WRITE | True
11:04:54   /db/pialert.db       |  READ  | True
11:04:54   /db/pialert.db       |  WRITE | True
11:04:54 ------------------------------------------------
11:04:54 [Setup] Attempting to fix permissions.
11:04:54 [Setup] Attempting to fix permissions.
11:04:54 [Database] Opening DB
11:04:54 [upgradeDB] Adding dev_Network_Node_MAC_ADDR to the Devices table
11:04:54 [upgradeDB] Adding dev_Network_Node_port to the Devices table
11:04:54 [upgradeDB] Adding dev_Icon to the Devices table
11:04:54 [upgradeDB] Re-creating Settings table
11:04:54 [upgradeDB] Re-creating Pholus_Scan table
11:04:54 [upgradeDB] Re-creating Parameters table
---------------------------------------------------------
[INSTALL]                                    Run start.sh
---------------------------------------------------------
sed: can't read /home/pi/pialert/back/pialert.conf_bak: No such file or directory
[INSTALL] Run setup scripts
---------------------------------------------------------
[INSTALL]                             Run user-mapping.sh
---------------------------------------------------------
USER_ID  : 1000
USER_GID : 1000
USER_HOME: 
TZ       : Europe/Berlin
chown: missing operand after '1000:1000 '
Try 'chown --help' for more information.
---------------------------------------------------------
[INSTALL]                     Run install_dependencies.sh
---------------------------------------------------------
Reading package lists...
Building dependency tree...
Reading state information...
tini is already the newest version (0.19.0-1).
snmp is already the newest version (5.9.3+dfsg-2).
ca-certificates is already the newest version (20230311).
curl is already the newest version (7.88.1-10+deb12u5).
libwww-perl is already the newest version (6.68-1).
arp-scan is already the newest version (1.10.0-2).
perl is already the newest version (5.36.0-7+deb12u1).
apt-utils is already the newest version (2.6.1).
cron is already the newest version (3.0pl1-162).
sudo is already the newest version (1.9.13p3-1+deb12u1).
nginx-light is already the newest version (1.22.1-9).
php is already the newest version (2:8.2+93).
php-cgi is already the newest version (2:8.2+93).
php-fpm is already the newest version (2:8.2+93).
php-sqlite3 is already the newest version (2:8.2+93).
php-curl is already the newest version (2:8.2+93).
sqlite3 is already the newest version (3.40.1-2).
dnsutils is already the newest version (1:9.18.19-1~deb12u1).
net-tools is already the newest version (2.10-0.1).
python3 is already the newest version (3.11.2-1+b1).
iproute2 is already the newest version (6.1.0-3).
nmap is already the newest version (7.93+dfsg1-1).
python3-pip is already the newest version (23.0.1+dfsg-1).
zip is already the newest version (3.0-13).
systemctl is already the newest version (1.4.4181-1.1).
usbutils is already the newest version (1:014-1).
traceroute is already the newest version (1:2.1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
nginx is already the newest version (1.22.1-9).
nginx-core is already the newest version (1.22.1-9).
mtr is already the newest version (0.95-1).
php-fpm is already the newest version (2:8.2+93).
php8.2-fpm is already the newest version (8.2.7-1~deb12u1).
php-cli is already the newest version (2:8.2+93).
php8.2 is already the newest version (8.2.7-1~deb12u1).
php8.2-sqlite3 is already the newest version (8.2.7-1~deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3.11-venv is already the newest version (3.11.2-6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: requests in /myenv/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: paho-mqtt in /myenv/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: scapy in /myenv/lib/python3.11/site-packages (2.5.0)
Requirement already satisfied: cron-converter in /myenv/lib/python3.11/site-packages (1.0.2)
Requirement already satisfied: pytz in /myenv/lib/python3.11/site-packages (2023.3.post1)
Requirement already satisfied: json2table in /myenv/lib/python3.11/site-packages (1.1.5)
Requirement already satisfied: dhcp-leases in /myenv/lib/python3.11/site-packages (0.1.6)
Requirement already satisfied: pyunifi in /myenv/lib/python3.11/site-packages (2.21)
Requirement already satisfied: speedtest-cli in /myenv/lib/python3.11/site-packages (2.1.3)
Requirement already satisfied: chardet in /myenv/lib/python3.11/site-packages (5.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /myenv/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /myenv/lib/python3.11/site-packages (from requests) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /myenv/lib/python3.11/site-packages (from requests) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /myenv/lib/python3.11/site-packages (from requests) (2023.11.17)
Requirement already satisfied: python-dateutil in /myenv/lib/python3.11/site-packages (from cron-converter) (2.8.2)
Requirement already satisfied: six>=1.5 in /myenv/lib/python3.11/site-packages (from python-dateutil->cron-converter) (1.16.0)
[INSTALL] Setup NGINX
Removing existing PiAlert web-UI
Removing existing PiAlert NGINX config
Setting webserver to user-supplied port (20212)
[INSTALL] Run the hardware vendors update
The file ieee-oui.txt exists. Skipping update_vendors.sh...
[INSTALL] Fixing file permissions
[INSTALL] Fixing WEB_UI_DIR: /var/www/html/pialert
[INSTALL] Fixing INSTALL_DIR: /home/pi
[INSTALL] Copy starter pialert.db and pialert.conf if they don't exist
[INSTALL] Fixing permissions after copied starter config & DB
Starting nginx: nginx.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pi/pialert/pialert/__main__.py", line 195, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/home/pi/pialert/pialert/__main__.py", line 89, in main
    importConfigs(db)
  File "/home/pi/pialert/pialert/initialise.py", line 69, in importConfigs
    renameSettings(config_file)
  File "/home/pi/pialert/pialert/initialise.py", line 271, in renameSettings
    with open(str(config_file), 'r') as original_file:  # Convert config_file to a string
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/pi/pialert/config/pialert.conf'
11:05:14 [MAIN] Setting up ...
11:05:14 [conf.tz] Setting up ...
      
 
11:05:14 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
      
 
11:05:14 Permissions check (All should be True)
11:05:14 ------------------------------------------------
11:05:14   /config/pialert.conf |  READ  | True
11:05:14   /config/pialert.conf |  WRITE | True
11:05:14   /db/pialert.db       |  READ  | True
11:05:14   /db/pialert.db       |  WRITE | True
11:05:14 ------------------------------------------------
11:05:14 [Setup] Attempting to fix permissions.
11:05:14 [Setup] Attempting to fix permissions.
11:05:14 [Database] Opening DB
11:05:14 [upgradeDB] Re-creating Settings table
11:05:14 [upgradeDB] Re-creating Pholus_Scan table
11:05:14 [upgradeDB] Re-creating Parameters table
---------------------------------------------------------
[INSTALL]                                    Run start.sh
---------------------------------------------------------
sed: can't read /home/pi/pialert/back/pialert.conf_bak: No such file or directory
[INSTALL] Run setup scripts
---------------------------------------------------------
[INSTALL]                             Run user-mapping.sh
---------------------------------------------------------
USER_ID  : 1000
USER_GID : 1000
USER_HOME: 
TZ       : Europe/Berlin
chown: missing operand after '1000:1000 '
Try 'chown --help' for more information.
---------------------------------------------------------
[INSTALL]                     Run install_dependencies.sh
---------------------------------------------------------
Reading package lists...
Building dependency tree...
Reading state information...
tini is already the newest version (0.19.0-1).
snmp is already the newest version (5.9.3+dfsg-2).
ca-certificates is already the newest version (20230311).
curl is already the newest version (7.88.1-10+deb12u5).
libwww-perl is already the newest version (6.68-1).
arp-scan is already the newest version (1.10.0-2).
perl is already the newest version (5.36.0-7+deb12u1).
apt-utils is already the newest version (2.6.1).
cron is already the newest version (3.0pl1-162).
sudo is already the newest version (1.9.13p3-1+deb12u1).
nginx-light is already the newest version (1.22.1-9).
php is already the newest version (2:8.2+93).
php-cgi is already the newest version (2:8.2+93).
php-fpm is already the newest version (2:8.2+93).
php-sqlite3 is already the newest version (2:8.2+93).
php-curl is already the newest version (2:8.2+93).
sqlite3 is already the newest version (3.40.1-2).
dnsutils is already the newest version (1:9.18.19-1~deb12u1).
net-tools is already the newest version (2.10-0.1).
python3 is already the newest version (3.11.2-1+b1).
iproute2 is already the newest version (6.1.0-3).
nmap is already the newest version (7.93+dfsg1-1).
python3-pip is already the newest version (23.0.1+dfsg-1).
zip is already the newest version (3.0-13).
systemctl is already the newest version (1.4.4181-1.1).
usbutils is already the newest version (1:014-1).
traceroute is already the newest version (1:2.1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
nginx is already the newest version (1.22.1-9).
nginx-core is already the newest version (1.22.1-9).
mtr is already the newest version (0.95-1).
php-fpm is already the newest version (2:8.2+93).
php8.2-fpm is already the newest version (8.2.7-1~deb12u1).
php-cli is already the newest version (2:8.2+93).
php8.2 is already the newest version (8.2.7-1~deb12u1).
php8.2-sqlite3 is already the newest version (8.2.7-1~deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3.11-venv is already the newest version (3.11.2-6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: requests in /myenv/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: paho-mqtt in /myenv/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: scapy in /myenv/lib/python3.11/site-packages (2.5.0)
Requirement already satisfied: cron-converter in /myenv/lib/python3.11/site-packages (1.0.2)
Requirement already satisfied: pytz in /myenv/lib/python3.11/site-packages (2023.3.post1)
Requirement already satisfied: json2table in /myenv/lib/python3.11/site-packages (1.1.5)
Requirement already satisfied: dhcp-leases in /myenv/lib/python3.11/site-packages (0.1.6)
Requirement already satisfied: pyunifi in /myenv/lib/python3.11/site-packages (2.21)
Requirement already satisfied: speedtest-cli in /myenv/lib/python3.11/site-packages (2.1.3)
Requirement already satisfied: chardet in /myenv/lib/python3.11/site-packages (5.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /myenv/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /myenv/lib/python3.11/site-packages (from requests) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /myenv/lib/python3.11/site-packages (from requests) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /myenv/lib/python3.11/site-packages (from requests) (2023.11.17)
Requirement already satisfied: python-dateutil in /myenv/lib/python3.11/site-packages (from cron-converter) (2.8.2)
Requirement already satisfied: six>=1.5 in /myenv/lib/python3.11/site-packages (from python-dateutil->cron-converter) (1.16.0)
[INSTALL] Setup NGINX
Removing existing PiAlert web-UI
Removing existing PiAlert NGINX config
Setting webserver to user-supplied port (20212)
[INSTALL] Run the hardware vendors update
The file ieee-oui.txt exists. Skipping update_vendors.sh...
[INSTALL] Fixing file permissions
[INSTALL] Fixing WEB_UI_DIR: /var/www/html/pialert
[INSTALL] Fixing INSTALL_DIR: /home/pi
[INSTALL] Copy starter pialert.db and pialert.conf if they don't exist
[INSTALL] Fixing permissions after copied starter config & DB
Starting nginx: nginx.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pi/pialert/pialert/__main__.py", line 195, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/home/pi/pialert/pialert/__main__.py", line 89, in main
    importConfigs(db)
  File "/home/pi/pialert/pialert/initialise.py", line 69, in importConfigs
    renameSettings(config_file)
  File "/home/pi/pialert/pialert/initialise.py", line 271, in renameSettings
    with open(str(config_file), 'r') as original_file:  # Convert config_file to a string
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/pi/pialert/config/pialert.conf'
11:05:35 [MAIN] Setting up ...
11:05:35 [conf.tz] Setting up ...
      
 
11:05:35 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
      ```

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by djzwerg** [comment]
Just for a test this image works like a charm: https://hub.docker.com/r/kenzok/pialert. But I want to use this (https://github.com/jokob-sk/Pi.Alert).

**Comment by jokob-sk** [comment]
Hi there @djzwerg !

Thanks for wanting to use my app.

You seem to be mounting the config directory to the config file:

```yaml
...
- /docker/pi-alert/config:/home/pi/pialert/config/pialert.conf
...
```

 That's why you are getting the error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pi/pialert/pialert/__main__.py", line 195, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/home/pi/pialert/pialert/__main__.py", line 89, in main
    importConfigs(db)
  File "/home/pi/pialert/pialert/initialise.py", line 69, in importConfigs
    renameSettings(config_file)
  File "/home/pi/pialert/pialert/initialise.py", line 271, in renameSettings
    with open(str(config_file), 'r') as original_file:  # Convert config_file to a string
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/pi/pialert/config/pialert.conf'
```

Depending on your file structure you probably need to change your docker-compose to:

```yaml
...
- /docker/pi-alert/config:/home/pi/pialert/config
...
```

Hope this helps,
j

**Comment by djzwerg** [comment]
Thanks @jokob-sk that was my mistake!

**Comment by jokob-sk** [comment]
Glad it works now :)
