### ISSUE TITLE
unable to open database: /etc/pihole/pihole-FTL.db

### ISSUE THREAD

**Issue by evan326** [jokob-sk/Pi.Alert#99]
Hi, I'm having the following errors and I can't figure out what to do about it. 
root owns the pihole db and www-data owns the pialert db
Any Ideas?
```
Pi.Alert 3.6_jokobsk (2022-08-03)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2022-10-03 13:05:00

Scanning...
    arp-scan Method...
    arp-scan: Multiple interfaces
    Pi-hole Method...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1817, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 96, in main
    res = scan_network()
  File "/home/pi/pialert/back/pialert.py", line 414, in scan_network
    copy_pihole_network()
  File "/home/pi/pialert/back/pialert.py", line 554, in copy_pihole_network
    sql.execute ("ATTACH DATABASE '"+ PIHOLE_DB +"' AS PH")
sqlite3.OperationalError: unable to open database: /etc/pihole/pihole-FTL.db
```
Here is my compose file also:
```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: always
    volumes:
      - /home/evan/pialert/config:/home/pi/pialert/config
      - /home/evan/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
      - /home/evan/pialert/log/:/home/pi/pialert/log
      
    environment:
      - TZ=America/New_York
      - PORT=20211
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
```

**Comment by evan326** [comment]
For anyone else as foolish as me: remember to also map the pihole db in the compose file...
